### PR TITLE
Fix the build of the Python bindings.

### PR DESCRIPTION
**Pull request by robquill**
When attempting the build the Python bindings like this:

```bash
cmake -DKOMPUTE_OPT_BUILD_PYTHON=ON ..
make
```

I get this error:

```
[100%] Linking CXX shared module ../lib/kp.cpython-310-x86_64-linux-gnu.so
lto-wrapper: warning: using serial compilation of 2 LTRANS jobs
/usr/bin/ld: ../lib/libfmt.a(format.cc.o): warning: relocation against `stdout@@GLIBC_2.2.5' in read-only section `.text'
/usr/bin/ld: ../lib/libkompute.a(Algorithm.cpp.o): relocation R_X86_64_PC32 against symbol `_ZTINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
make[2]: *** [python/CMakeFiles/kp.dir/build.make:102: lib/kp.cpython-310-x86_64-linux-gnu.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:373: python/CMakeFiles/kp.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
```

### CODE REVIEW

**Comment by axsaucedo** [comment]
The python build is supposed to be built through the setup.py, and is not maintained for other use-cases - could you expand what this flag would do and why it would be needed? I'd rather this is something that is passed through the command line if people want to do this themselves as opposed to adding it to the core build for all targets

**Comment by axsaucedo** [comment]
Thank you for the contribution @robquill - this could make sense, but could you expand what this flag would do in context of the broader codebase? Asking as if it's more of a corner case for a particular use-case, it may make more sense adding this on the respective project cmake file as opposed to by default to the repo to all targets

**Comment by robquill** [comment]
My understanding is that building a shared object requires position-independent code (https://stackoverflow.com/questions/57649452/why-must-shared-libraries-be-position-independent-while-static-libraries-dont), so I could try only setting this option if -DKOMPUTE_OPT_BUILD_PYTHON=ON is set.

I don't think you can only set it e.g. for the Pybind11 module itself as that shared library is still built using the static libraries which would still contain position dependent code.

**Comment by axsaucedo** [comment]
> so I could try only setting this option if -DKOMPUTE_OPT_BUILD_PYTHON=ON is set
From my understanding position independent code is glowingly the default in more modern distros, and it may indeed be the case that restricting it to only -DKOMPUTE_OPT_BUILD_PYTHON=ON may be the way to go, as I can't think of a corner case at this stage (unless someone wants to build static vs dynamic version of python although haven't tried if possible)

**Comment by robquill** [comment]
> > so I could try only setting this option if -DKOMPUTE_OPT_BUILD_PYTHON=ON is set
> 
> From my understanding position independent code is glowingly the default in more modern distros, and it may indeed be the case that restricting it to only -DKOMPUTE_OPT_BUILD_PYTHON=ON may be the way to go, as I can't think of a corner case at this stage (unless someone wants to build static vs dynamic version of python although haven't tried if possible)

OK then, that is already done, so I think this should be good to go.

**Review by axsaucedo — APPROVED** [review]
LGTM

**Pull request merged**
